sudo: true
dist: trusty
language:
  - generic
cache:
  - apt

env:
  global:
    - ROS_DISTRO=indigo
    - ROS_CI_DESKTOP="`lsb_release -cs`"
    - CI_SOURCE_PATH=$(pwd)

# Install package dependencies
before_install:
  - echo "Testing branch $TRAVIS_BRANCH "
  - pwd
  # Install OpenRAVE
  - mkdir -p ~/git; cd ~/git
  - git clone https://github.com/crigroup/openrave-installation.git
  - cd openrave-installation
  - ./install-dependencies.sh
  - ./install-fcl.sh
  - ./install-openrave.sh
  # Install ROS
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # Prepare rosdep to install dependencies.
  - sudo rosdep init
  - rosdep update
  # Install coveralls
  - pip install coveralls --user

# Create a catkin workspace with the package under integration.
install:
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - cd ~/catkin_ws
  - catkin_make
  - source devel/setup.bash
  - cd ~/catkin_ws/src
  - wstool init .
  - wstool merge https://raw.github.com/crigroup/robotsp/$TRAVIS_BRANCH/robotsp.rosinstall
  - wstool update
  # Delete the .rosinstall version and use the branch we are testing
  - rm -rf robotsp/
  - ln -s $CI_SOURCE_PATH .
  # When installing from source, you need the latest version of these pkgs
  - git clone https://github.com/crigroup/baldor.git
  - git clone https://github.com/crigroup/criutils.git
  - git clone https://github.com/crigroup/lkh.git

# Install all dependencies
before_script:
  - cd ~/catkin_ws
  - rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO

# Compile
script:
  - cd ~/catkin_ws
  - catkin_make
  - source devel/setup.bash
  - cd ~/catkin_ws/src/robotsp
  # Run the tests with coverage
  - nosetests tests/ --with-coverage --cover-package=robotsp -v

after_success:
  - coveralls
